// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vocabulary.Infrastructure.Data;

#nullable disable

namespace Vocabulary.Infrastructure.Migrations
{
    [DbContext(typeof(VocabularyDbContext))]
    [Migration("20251205151757_UserWordList_And_UserWord_Class_Name_Updated")]
    partial class UserWordList_And_UserWord_Class_Name_Updated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vocabulary.Core.Entities.UserWord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Meaning")
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserWordListId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserWordListId");

                    b.ToTable("Words");
                });

            modelBuilder.Entity("Vocabulary.Core.Entities.UserWordList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("UserWordLists");
                });

            modelBuilder.Entity("Vocabulary.Core.Entities.UserWord", b =>
                {
                    b.HasOne("Vocabulary.Core.Entities.UserWordList", null)
                        .WithMany("UserWords")
                        .HasForeignKey("UserWordListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vocabulary.Core.Entities.UserWordList", b =>
                {
                    b.Navigation("UserWords");
                });
#pragma warning restore 612, 618
        }
    }
}
