// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TextGen.Infrastructure.Data;

#nullable disable

namespace TextGen.Infrastructure.Migrations
{
    [DbContext(typeof(TextGenDbContext))]
    [Migration("20260105114915_Add_Properties_To_GeneratedText")]
    partial class Add_Properties_To_GeneratedText
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TextGen.Core.Entities.GeneratedText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedReadingTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("GeneratedTexts");
                });

            modelBuilder.Entity("TextGen.Core.Entities.GeneratedTextKeyword", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GeneratedTextRequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("Keyword")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedTextRequestId");

                    b.ToTable("GeneratedTextKeywords");
                });

            modelBuilder.Entity("TextGen.Core.Entities.GeneratedTextRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GeneratedTextId")
                        .HasColumnType("uuid");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("GeneratedTextId")
                        .IsUnique();

                    b.ToTable("GeneratedTextRequests");
                });

            modelBuilder.Entity("TextGen.Core.Entities.PublicText", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EstimatedReadingTimeMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WordCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("PublicTexts");
                });

            modelBuilder.Entity("TextGen.Core.Entities.SuggestedTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SuggestedTopics");
                });

            modelBuilder.Entity("TextGen.Core.Entities.GeneratedText", b =>
                {
                    b.OwnsMany("TextGen.Core.Entities.TextQuizItem", "Quiz", b1 =>
                        {
                            b1.Property<Guid>("GeneratedTextId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("CorrectAnswer");

                            b1.PrimitiveCollection<string>("Options")
                                .IsRequired();

                            b1.Property<string>("Question")
                                .IsRequired();

                            b1.HasKey("GeneratedTextId", "__synthesizedOrdinal");

                            b1.ToTable("GeneratedTexts");

                            b1.ToJson("Quiz");

                            b1.WithOwner()
                                .HasForeignKey("GeneratedTextId");
                        });

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("TextGen.Core.Entities.GeneratedTextKeyword", b =>
                {
                    b.HasOne("TextGen.Core.Entities.GeneratedTextRequest", "GeneratedTextRequest")
                        .WithMany("Keywords")
                        .HasForeignKey("GeneratedTextRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedTextRequest");
                });

            modelBuilder.Entity("TextGen.Core.Entities.GeneratedTextRequest", b =>
                {
                    b.HasOne("TextGen.Core.Entities.GeneratedText", "GeneratedText")
                        .WithOne("Request")
                        .HasForeignKey("TextGen.Core.Entities.GeneratedTextRequest", "GeneratedTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GeneratedText");
                });

            modelBuilder.Entity("TextGen.Core.Entities.PublicText", b =>
                {
                    b.OwnsMany("TextGen.Core.Entities.PublicTextQuizItem", "Quiz", b1 =>
                        {
                            b1.Property<Guid>("PublicTextId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<int>("CorrectAnswer");

                            b1.PrimitiveCollection<string>("Options")
                                .IsRequired();

                            b1.Property<string>("Question")
                                .IsRequired();

                            b1.HasKey("PublicTextId", "__synthesizedOrdinal");

                            b1.ToTable("PublicTexts");

                            b1.ToJson("Quiz");

                            b1.WithOwner()
                                .HasForeignKey("PublicTextId");
                        });

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("TextGen.Core.Entities.GeneratedText", b =>
                {
                    b.Navigation("Request")
                        .IsRequired();
                });

            modelBuilder.Entity("TextGen.Core.Entities.GeneratedTextRequest", b =>
                {
                    b.Navigation("Keywords");
                });
#pragma warning restore 612, 618
        }
    }
}
